#!/nix/store/wv35g5lff84rray15zlzarcqi9fxzz84-bash-4.4-p23/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_motion_interval 40
bspc config focused_border_color '#6B440E'
bspc config normal_border_color '#201007'

bspc rule -a Firefox:firefox state=floating rectangle=400x375+0+0 center=on
bspc rule -a Firefox:Navigator state=tiled

bspc rule -a Screenkey manage=off

mpd &
picom &
xset -dpms s off &						# Impedir que a tela apague
nitrogen --restore &
xsetroot -cursor_name left_ptr &				# Arrumar bug onde aparece um X no cursor no desktop
